version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    command: flask run 0.0.0.0:5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ./.env
    depends_on:
      - mongo

volumes:
  mongo_data:
